name: 编译 Emuelec 固件

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 编译 Emuelec 固件
        run: |
          echo 开始编译固件
          sudo apt-get update -y
          sudo apt-get full-upgrade -y
          sudo apt install -y tzdata xfonts-utils lzop 
          sudo apt install -y unzip wget xz-utils libsdl2-dev libsdl2-mixer-dev libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev rapidjson-dev libasound2-dev libgl1-mesa-dev build-essential libboost-all-dev cmake fonts-droid-fallback libvlc-dev libvlccore-dev vlc-bin texinfo premake4 golang libssl-dev curl patchelf xmlstarlet default-jre xsltproc
          sudo apt install -y libparse-yapp-perl gperf libxml-parser-perl patchutils
          PROJECT=Amlogic-ce DEVICE=Amlogic-ng ARCH=aarch64 DISTRO=EmuELEC make image
