name: 编译 Emuelec 固件

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 编译 Emuelec 固件
        run: |
          echo 开始编译固件
          sudo apt-get update -y
          sudo apt-get full-upgrade -y
          sudo apt install -y tzdata xfonts-utils lzop 
          PROJECT=Amlogic-ce DEVICE=Amlogic-ng ARCH=aarch64 DISTRO=EmuELEC make image
